// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RayonGuinda.Context;

#nullable disable

namespace RayonGuinda.Migrations
{
    [DbContext(typeof(RayonguindaContext))]
    partial class RayonguindaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArchivoTarea", b =>
                {
                    b.Property<int>("CalificacionId")
                        .HasColumnType("int")
                        .HasColumnName("Calificacion_ID");

                    b.Property<int>("TareaId")
                        .HasColumnType("int")
                        .HasColumnName("Tarea_ID");

                    b.HasKey("CalificacionId", "TareaId")
                        .HasName("PK__Archivo___A74C19A604536A11");

                    b.HasIndex("TareaId");

                    b.ToTable("Archivo_Tarea", (string)null);
                });

            modelBuilder.Entity("CalificacionTarea", b =>
                {
                    b.Property<int>("CalificacionId")
                        .HasColumnType("int")
                        .HasColumnName("Calificacion_ID");

                    b.Property<int>("TareaId")
                        .HasColumnType("int")
                        .HasColumnName("Tarea_ID");

                    b.HasKey("CalificacionId", "TareaId")
                        .HasName("PK__Califica__A74C19A6C244FCF0");

                    b.HasIndex("TareaId");

                    b.ToTable("Calificacion_Tarea", (string)null);
                });

            modelBuilder.Entity("PublicacionForo", b =>
                {
                    b.Property<int>("PublicacionId")
                        .HasColumnType("int")
                        .HasColumnName("Publicacion_ID");

                    b.Property<int>("ForoId")
                        .HasColumnType("int")
                        .HasColumnName("Foro_ID");

                    b.HasKey("PublicacionId", "ForoId")
                        .HasName("PK__Publicac__CC48EC988C53B95B");

                    b.HasIndex("ForoId");

                    b.ToTable("Publicacion_Foro", (string)null);
                });

            modelBuilder.Entity("RayonGuinda.Models.ArchivoModel", b =>
                {
                    b.Property<int>("ArchivoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Archivo_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArchivoId"));

                    b.Property<string>("AlumnoResponsable")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Alumno_Responsable");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_Publicacion");

                    b.Property<int>("PesoArchivo")
                        .HasColumnType("int")
                        .HasColumnName("Peso_Archivo");

                    b.HasKey("ArchivoId")
                        .HasName("PK__Archivo__E5AC051F0605F552");

                    b.ToTable("Archivo", (string)null);
                });

            modelBuilder.Entity("RayonGuinda.Models.CalificacionModel", b =>
                {
                    b.Property<int>("CalificacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Calificacion_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CalificacionId"));

                    b.Property<string>("AlumnoCalificacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Alumno_Calificacion");

                    b.Property<int>("Calificacion1")
                        .HasColumnType("int")
                        .HasColumnName("Calificacion");

                    b.HasKey("CalificacionId")
                        .HasName("PK__Califica__146BB23EC50181B5");

                    b.ToTable("Calificacion", (string)null);
                });

            modelBuilder.Entity("RayonGuinda.Models.ChatModel", b =>
                {
                    b.Property<int>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Chat_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OtherUser")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Other_user");

                    b.HasKey("ChatId")
                        .HasName("PK__Chat__9783B1FE4453F6A4");

                    b.ToTable("Chat", (string)null);
                });

            modelBuilder.Entity("RayonGuinda.Models.ComentarioModel", b =>
                {
                    b.Property<int>("ComentarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Comentario_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComentarioId"));

                    b.Property<string>("AutorComentario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Autor_Comentario");

                    b.Property<string>("ContenidoComentario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Contenido_Comentario");

                    b.Property<int>("PublicacionId")
                        .HasColumnType("int")
                        .HasColumnName("Publicacion_ID");

                    b.HasKey("ComentarioId")
                        .HasName("PK__Comentar__6551412944FA7B88");

                    b.HasIndex("PublicacionId");

                    b.ToTable("Comentario", (string)null);
                });

            modelBuilder.Entity("RayonGuinda.Models.ForoModel", b =>
                {
                    b.Property<int>("ForoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Foro_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ForoId"));

                    b.Property<string>("Administrador")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NombreForo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Nombre_Foro");

                    b.Property<int>("NumIntegrantes")
                        .HasColumnType("int")
                        .HasColumnName("Num_Integrantes");

                    b.HasKey("ForoId")
                        .HasName("PK__Foro__FB62CCA3355C49F8");

                    b.ToTable("Foro", (string)null);
                });

            modelBuilder.Entity("RayonGuinda.Models.GrupoModel", b =>
                {
                    b.Property<int>("GrupoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Grupo_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GrupoId"));

                    b.Property<int>("AdminID")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<string>("ClaveAcceso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Clave_Acceso");

                    b.Property<string>("NombreGrupo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Nombre_Grupo");

                    b.Property<int>("NumIntegrantes")
                        .HasColumnType("int")
                        .HasColumnName("Num_Integrantes");

                    b.HasKey("GrupoId")
                        .HasName("PK__Grupo__BE194F08DB4A143C");

                    b.ToTable("Grupo", (string)null);
                });

            modelBuilder.Entity("RayonGuinda.Models.ParticipanteModel", b =>
                {
                    b.Property<int>("IndexUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Index_user");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IndexUser"));

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Nombre_Completo");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IndexUser")
                        .HasName("PK__Particip__0838B1DF216C7E01");

                    b.ToTable("Participantes");
                });

            modelBuilder.Entity("RayonGuinda.Models.PublicacionModel", b =>
                {
                    b.Property<int>("PublicacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Publicacion_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PublicacionId"));

                    b.Property<string>("AutorPublicacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Autor_Publicacion");

                    b.Property<string>("ContenidoPublicacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Contenido_Publicacion");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_Publicacion");

                    b.HasKey("PublicacionId")
                        .HasName("PK__Publicac__E3FEC052ECCCA370");

                    b.ToTable("Publicacion", (string)null);
                });

            modelBuilder.Entity("RayonGuinda.Models.TareaModel", b =>
                {
                    b.Property<int>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Tarea_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TareaId"));

                    b.Property<string>("AutorPublicacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Autor_Publicacion");

                    b.Property<int>("Calificar")
                        .HasColumnType("int");

                    b.Property<string>("ContenidoPublicacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Contenido_Publicacion");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_Publicacion");

                    b.HasKey("TareaId")
                        .HasName("PK__Tarea__327AB98A18E2ABB1");

                    b.ToTable("Tarea", (string)null);
                });

            modelBuilder.Entity("RayonGuinda.Models.UsuarioModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("User_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Apellido_Materno");

                    b.Property<string>("ApellidoPaterno")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Apellido_Paterno");

                    b.Property<string>("Contraseña")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CorreoInstitucional")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Correo_Institucional");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha_Nacimiento");

                    b.Property<string>("Nombres")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NumBoleta")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Num_Boleta");

                    b.HasKey("UserId")
                        .HasName("PK__Usuario__206D9190B281C9D9");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("UsuarioChat", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_ID");

                    b.Property<int>("ChatId")
                        .HasColumnType("int")
                        .HasColumnName("Chat_ID");

                    b.HasKey("UserId", "ChatId")
                        .HasName("PK__Usuario___D915AA8FDF95BA20");

                    b.HasIndex("ChatId");

                    b.ToTable("Usuario_Chat", (string)null);
                });

            modelBuilder.Entity("UsuarioForo", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_ID");

                    b.Property<int>("ForoId")
                        .HasColumnType("int")
                        .HasColumnName("Foro_ID");

                    b.HasKey("UserId", "ForoId")
                        .HasName("PK__Usuario___0FDBBD5AF8733CB7");

                    b.HasIndex("ForoId");

                    b.ToTable("Usuario_Foro", (string)null);
                });

            modelBuilder.Entity("UsuarioGrupo", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_ID");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int")
                        .HasColumnName("Grupo_ID");

                    b.HasKey("UserId", "GrupoId")
                        .HasName("PK__Usuario___BB8C056025A0417F");

                    b.HasIndex("GrupoId");

                    b.ToTable("Usuario_Grupo", (string)null);
                });

            modelBuilder.Entity("ArchivoTarea", b =>
                {
                    b.HasOne("RayonGuinda.Models.CalificacionModel", null)
                        .WithMany()
                        .HasForeignKey("CalificacionId")
                        .IsRequired()
                        .HasConstraintName("FK__Archivo_T__Calif__6D0D32F4");

                    b.HasOne("RayonGuinda.Models.TareaModel", null)
                        .WithMany()
                        .HasForeignKey("TareaId")
                        .IsRequired()
                        .HasConstraintName("FK__Archivo_T__Tarea__6E01572D");
                });

            modelBuilder.Entity("CalificacionTarea", b =>
                {
                    b.HasOne("RayonGuinda.Models.CalificacionModel", null)
                        .WithMany()
                        .HasForeignKey("CalificacionId")
                        .IsRequired()
                        .HasConstraintName("FK__Calificac__Calif__70DDC3D8");

                    b.HasOne("RayonGuinda.Models.TareaModel", null)
                        .WithMany()
                        .HasForeignKey("TareaId")
                        .IsRequired()
                        .HasConstraintName("FK__Calificac__Tarea__71D1E811");
                });

            modelBuilder.Entity("PublicacionForo", b =>
                {
                    b.HasOne("RayonGuinda.Models.ForoModel", null)
                        .WithMany()
                        .HasForeignKey("ForoId")
                        .IsRequired()
                        .HasConstraintName("FK__Publicaci__Foro___628FA481");

                    b.HasOne("RayonGuinda.Models.PublicacionModel", null)
                        .WithMany()
                        .HasForeignKey("PublicacionId")
                        .IsRequired()
                        .HasConstraintName("FK__Publicaci__Publi__619B8048");
                });

            modelBuilder.Entity("RayonGuinda.Models.ComentarioModel", b =>
                {
                    b.HasOne("RayonGuinda.Models.PublicacionModel", "Publicacion")
                        .WithMany("Comentarios")
                        .HasForeignKey("PublicacionId")
                        .IsRequired()
                        .HasConstraintName("FK__Comentari__Publi__534D60F1");

                    b.Navigation("Publicacion");
                });

            modelBuilder.Entity("UsuarioChat", b =>
                {
                    b.HasOne("RayonGuinda.Models.ChatModel", null)
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .IsRequired()
                        .HasConstraintName("FK__Usuario_C__Chat___6A30C649");

                    b.HasOne("RayonGuinda.Models.UsuarioModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Usuario_C__User___693CA210");
                });

            modelBuilder.Entity("UsuarioForo", b =>
                {
                    b.HasOne("RayonGuinda.Models.ForoModel", null)
                        .WithMany()
                        .HasForeignKey("ForoId")
                        .IsRequired()
                        .HasConstraintName("FK__Usuario_F__Foro___5EBF139D");

                    b.HasOne("RayonGuinda.Models.UsuarioModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Usuario_F__User___5DCAEF64");
                });

            modelBuilder.Entity("UsuarioGrupo", b =>
                {
                    b.HasOne("RayonGuinda.Models.GrupoModel", null)
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .IsRequired()
                        .HasConstraintName("FK__Usuario_G__Grupo__66603565");

                    b.HasOne("RayonGuinda.Models.UsuarioModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Usuario_G__User___656C112C");
                });

            modelBuilder.Entity("RayonGuinda.Models.PublicacionModel", b =>
                {
                    b.Navigation("Comentarios");
                });
#pragma warning restore 612, 618
        }
    }
}
